import type { Metadata } from "next";
import { Lora, Gabarito, Cormorant_Upright, Aleo } from "next/font/google";
import "./globals.css";

const lora = Lora(
  {
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-lora",
  }
)

const gabarito = Gabarito({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-gabarito",
})

const cormorantUpright = Cormorant_Upright({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-cormorant-upright",
})

const aleo = Aleo({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-aleo"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${gabarito.variable} ${cormorantUpright.variable} ${aleo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
